on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
        - run: node --version
        - uses: actions/checkout@main
          with:
            submodules: recursive
        - run: sudo apt install emscripten bison # bison is for gawk
        - run: make test

    mac:
        runs-on: macOS-latest
        steps:
        - run: node --version
        - uses: actions/checkout@main
          with:
            submodules: recursive
        - run: brew install emscripten bison
        - run: make test
